-- Atomic per-branch counters for receipt numbers and trainee codes.
--
-- Both were generated by reading the branch's current maximum and adding one.
-- Concurrent requests read the same maximum and computed the same next value;
-- the unique formatted number then rejected all but one. Reproduced: six
-- simultaneous enrollments in one branch, FOUR failed with a duplicate-entry
-- error. The code claimed doing the read "inside the same transaction" made it
-- safe — it did not, because a transaction does not lock rows it only reads.
--
-- The application now takes the next value with
--
--     UPDATE branches SET receipt_seq = receipt_seq + 1 WHERE id = $1 RETURNING receipt_seq
--
-- whose row lock serializes concurrent requests. The increment rolls back with
-- its transaction, so the sequence stays gap-free across failures.
--
-- The DDL below (column adds, index swap) is exactly what `prisma migrate diff`
-- generates for schema.prisma, so there is no drift; the backfill and the guard
-- are hand-written around it.

-- 1. The counters.
ALTER TABLE "branches" ADD COLUMN     "receipt_seq" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "trainee_seq" INTEGER NOT NULL DEFAULT 0;

-- 2. Continue receipt numbering from where each branch already is.
--
-- ⚠️ ARCHIVED receipts count too. The old MAX(seq) read only the live table, so
-- once the archive job moved old receipts out, the maximum would drop and
-- receipt numbers would be REUSED — with uniqueness enforced only on the live
-- table, nothing would have stopped it. A counter that only increases removes
-- that possibility, as long as it starts above every number ever issued.
UPDATE "branches" b
SET "receipt_seq" = GREATEST(
  COALESCE((SELECT MAX(r."seq") FROM "receipts" r          WHERE r."branch_id" = b."id"), 0),
  COALESCE((SELECT MAX(a."seq") FROM "archived_receipts" a WHERE a."branch_id" = b."id"), 0)
);

-- 3. Continue trainee numbering from the highest existing code in each branch.
-- The numeric part is the trailing digits, whatever prefix a code carries —
-- an old prefixed code (`XYZ-BR01-000042`) and the new `BR01-000043` both parse.
UPDATE "branches" b
SET "trainee_seq" = COALESCE((
  SELECT MAX(CAST(substring(t."system_code" FROM '([0-9]+)$') AS INTEGER))
  FROM "trainee_profiles" t
  WHERE t."branch_id" = b."id" AND t."system_code" ~ '[0-9]+$'
), 0);

-- 4. Refuse to proceed if a branch already has duplicate receipt sequence
-- numbers, rather than renumbering receipts. Receipts are financial records;
-- rewriting their numbers is not a migration's decision. Possible only if a
-- branch's code was changed after receipts were issued, since the old
-- uniqueness applied to the formatted number, not the sequence.
DO $$
DECLARE
  offenders integer;
BEGIN
  SELECT COUNT(*) INTO offenders
  FROM (
    SELECT "branch_id", "seq" FROM "receipts"
    GROUP BY "branch_id", "seq" HAVING COUNT(*) > 1
  ) duplicated;

  IF offenders > 0 THEN
    RAISE EXCEPTION
      'Cannot make receipt sequence unique per branch: % (branch, seq) pair(s) are duplicated. '
      'Resolve them first, then re-run. Find them with: SELECT branch_id, seq, COUNT(*) '
      'FROM receipts GROUP BY branch_id, seq HAVING COUNT(*) > 1;',
      offenders;
  END IF;
END $$;

-- 5. Make the sequence itself unique per branch, not just the number derived
-- from it. (Generated by Prisma.)
DROP INDEX "receipts_branch_id_seq_idx";

CREATE UNIQUE INDEX "receipts_branch_id_seq_key" ON "receipts"("branch_id", "seq");
